### ISSUE TITLE
tk ImportError

### ISSUE THREAD

**Issue by cbehn1** [sandialabs/spat#1]
```
$ python spat.py
Traceback (most recent call last):
  File "spat.py", line 43, in <module>
    from Tkinter import *
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
```

**Comment by jafeelv** [comment]
The error message suggests that you need to install the python-tk package in order to use the Tkinter library in Python 2.7.

You can install the python-tk package by running the following command in your terminal or command prompt: 
> sudo apt-get install python-tk

This will install the package and its dependencies on your system.
Once the package is installed, you should be able to import the Tkinter module without getting the _tkinter ImportError.
